# Generated by Django 4.1.4 on 2022-12-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_remove_player_image_player_images_player_nickname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='images',
        ),
        migrations.AddField(
            model_name='player',
            name='image1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='image2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='image3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='image4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
